spring:
  data:
    mongodb:
      uri: mongodb://root:123456789@localhost:27017/spring-poi-db?authSource=admin

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB